### ISSUE TITLE
[Issue] Collums for server folders

### ISSUE THREAD

**Issue by SaengerItsWar** [NFLD99/Better-Discord#40]
Hello i'm current using your themes and some day the second collum for the server folders stoped working.
Also Deactivated all Plugins except of your plugin.
so i mean the direct server folders.
![Screenshot_56](https://user-images.githubusercontent.com/13980351/82574476-7db31500-9b87-11ea-9c1d-f6b7b90ca3c4.png)

**Comment by TwinDragon** [comment]
This is a limitation currently in the Discord CSS. Ever since Discord released native folders, there was a compromise that had to be done months ago, so that's just something we all have to deal with for those using more than 1 column. It's not ideal, but at this time, there's nothing that can be done about it.

**Comment by SaengerItsWar** [comment]
oh ok thanks for the info
